# Generated by Django 5.2.6 on 2025-10-03 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_remove_asistente_minimum_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistantProfile',
            fields=[
            ],
            options={
                'verbose_name': 'Asistente (Perfil)',
                'verbose_name_plural': 'Asistentes (Perfiles)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.userprofile',),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('authentication.userprofile',),
        ),
    ]
