# Generated by Django 5.2.6 on 2025-10-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_assistantprofile_student'),
        ('authentication', '0009_assistantprofile_student_alter_asistente_options_and_more'),
    ]

    operations = [
    ]
