# Generated by Django 5.2.6 on 2025-10-09 02:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_create_assistant_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfiguration',
            name='minutes_after_start',
            field=models.IntegerField(default=25, help_text='Tiempo límite en minutos después del inicio del evento para registrar asistencia (0-120)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(120)], verbose_name='Minutos después del inicio'),
        ),
        migrations.AddField(
            model_name='systemconfiguration',
            name='minutes_before_event',
            field=models.IntegerField(default=10, help_text='Tiempo en minutos antes del inicio del evento para permitir el registro de asistencia (0-60)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(60)], verbose_name='Minutos antes del evento'),
        ),
    ]
