# Generated by Django 5.2.6 on 2025-10-20 21:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0013_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='externaluser',
            name='account_number',
            field=models.CharField(max_length=8, unique=True, verbose_name='Número de cuenta'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='account_number',
            field=models.CharField(max_length=8, unique=True, validators=[django.core.validators.RegexValidator(message='El número de cuenta debe tener exactamente 8 dígitos.', regex='^\\d{8}$')], verbose_name='Número de cuenta'),
        ),
    ]
